import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const { maskCustomProperties } = await import(pathToFileURL(join(root, 'src/masks.ts')).href)

const css = `/* Generated by scripts/emit-masks.mjs — do not edit by hand. */\n${maskCustomProperties()}\n`

writeFileSync(join(root, 'src/masks.css'), css)
console.log('wrote src/masks.css')
